import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import TradeoffChart from '../../components/charts/TradeoffChart.jsx';
import CandidateDetail from '../../components/candidates/CandidateDetail.jsx';
import CandidateTable from '../../components/candidates/CandidateTable.jsx';
import { Badge, ErrorMessage, Spinner } from '../../components/common/Feedback.jsx';
import { useJob } from '../../hooks/useJob.js';

export default function Candidates() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { job, error } = useJob(id);
  const [tab, setTab] = useState('novel_candidates');
  const [selected, setSelected] = useState([]);
  const [open, setOpen] = useState(null);

  const toggle = (cid) => setSelected((s) => (s.includes(cid) ? s.filter((x) => x !== cid) : [...s, cid].slice(-6)));

  if (error) return <ErrorMessage error={error} />;
  if (!job) return <Spinner />;
  if (job.status === 'running') return <><h1>Discovery job #{job.id}</h1><Spinner label="Screening and ranking candidates…" /></>;
  if (job.status === 'failed') return <><h1>Discovery job #{job.id}</h1><ErrorMessage error={new Error(job.error)} /><Link to="/discovery">← New discovery</Link></>;

  const list = job[tab];
  const s = job.stats;
  return (
    <>
      <p><Link to="/discovery">← New discovery</Link></p>
      <h1>Discovery job #{job.id} <Badge tone="good">completed</Badge></h1>
      <p className="muted">
        Screened {s.known_considered} known + {s.generated_considered} generated compositions; {s.satisfied_requirements} satisfy the requirements.
        {' '}Validation runs down the ranking and rejected {s.failed_validation} on the way to the top results. Model {job.model_version}.
      </p>

      <div className="tabs" role="tablist">
        <button role="tab" aria-selected={tab === 'novel_candidates'} onClick={() => setTab('novel_candidates')}>
          Novel candidates (top {job.novel_candidates.length} of {s.generated_kept})
        </button>
        <button role="tab" aria-selected={tab === 'known_matches'} onClick={() => setTab('known_matches')}>
          Known matches (top {job.known_matches.length} of {s.known_kept})
        </button>
      </div>
      {tab === 'novel_candidates' && (
        <p className="muted small">Generated by element substitution and scored by the model — hypotheses to check, not confirmed materials. “Front” = Pareto-optimal trade-off between hitting the target and prediction certainty.</p>
      )}

      <TradeoffChart candidates={list} selectedId={open?.id} onSelect={setOpen} />
      <div className="split">
        <CandidateTable candidates={list} selected={selected} onToggle={toggle} onOpen={setOpen} openId={open?.id} />
        <CandidateDetail candidate={open} />
      </div>
      <button disabled={selected.length < 2} onClick={() => navigate(`/compare?ids=${selected.join(',')}`)}>
        Compare selected ({selected.length})
      </button>
    </>
  );
}
